---
title: Research #'{{< animate bounceInDown "Research" duration-faster >}}'
comments: false
# margin-header: "[Research](https://harrisq.github.io/research/) © 2024 by [Harris Quach](https://forbo7.github.io/about.html) is licensed under [CC
# BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1)"
listing:
  - id: pages
    contents: pages
    sort:
      - "title desc"
      - "date desc"
    categories: true
    sort-ui: [date, author]
    filter-ui: [title, date, auther]
    type: grid
    grid-columns: 3
    grid-item-border: true
    grid-item-align: left
    image-height: 100%
    date-format: "dddd, DD MMMM YYYY | YYYY-MM-DD"
format:
  html:
    page-layout: full
open-graph:
  description: "Here you can find my research, projects, and presentations."
twitter-card:
  description: "Here you can find some extended discussions and demonstrations or examples."
back-to-top-navigation: false
---

Here you can find my ongoing and past research, projects, and presentations.

<!-- :::{.animate__animated .animate__bounceInUp .animate__duration-faster} -->


<!-- Here you can find my ongoing and past research, projects, and presentations. -->

<!--  {{< animate fadeInDown 'Here you can find my ongoing and past research, projects, and presentations.' >}} --> 


<!-- ::: -->

:::{.panel-tabset}

# Research


### Methodology

* Quach, H., Yang, W, and Guo, W. "Adaptive Knot Selection for Refined Functional Sliced Inverse Regression". 2024. Ongoing

* Quach, H., Yang, W, and Guo, W. "Refining Functional Sliced Inverse Regression Using Informed Basis Expansions". 2024. Manuscript.

* Quach, H. and Li, B. "On Forward Sufficient Dimension Reduction for Categorical and Ordinal Responses". Electron. J. Statist. 17 (1) 980 - 1006, 2023. https://doi.org/10.1214/23-EJS2122. [Link](https://projecteuclid.org/journals/electronic-journal-of-statistics/volume-17/issue-1/On-forward-sufficient-dimension-reduction-for-categorical-and-ordinal-responses/10.1214/23-EJS2122.full?tab=ArticleLink). [supplement](supplements/supplementary_materials_opcg.pdf)


<!-- ### Collaborations -->

<!-- * Quach, H., Deo, R., Yang, W., and Guo, W. "Longitudinal changes in informative features of ECGs for cardiovascular disease progression". Ongoing. -->

<!-- Nabbout, M. Caporale, A., Langham, M., * Quach, H., Guo, W., Chatterjee, S., Wehrli, W.F. (2024)
“Effects of non-nicotine Electronic Cigarette Aerosol Inhalation on Vascular Function.” Ongoing -->


# Presentations

* Functional Sliced Inverse Regression via Informed Basis Expansions, 2024 August 4. 
  *2024 Joint Statistical Meeting* (Portland, Oregon, USA) &nbsp; 

* Functional Sliced Inverse Regression via Informed Basis Expansions, 2024 July 17.
  *2024 ECOSTA* (Bejing, China) &nbsp; 

* Smoothed Functional Sliced Inverse Regression with Applications to the CRIC Study, 2023 August 8. 
  *2023 Joint Statistical Meeting* (Toronto, Canada) &nbsp; 

* On Forward Sufficient Dimension Reduction for Categorical and Ordinal Responses, 2022 August 7. 
  *2022 Joint Statistical Meeting* (Washington, D.C.) &nbsp;<!-- [Slides](/slides/opcg/jsm_opcg#1) -->

* On Forward Sufficient Dimension Reduction for Categorical and Ordinal Responses, 2022 April 4. 
  *Fred Hutchison Post-Doc Seminar* (Remote) &nbsp;<!--[Slides](/slides/opcg/fred_hutch_opcg#1) -->

* Forward Sufficient Dimension Reduction for Categorical and Ordinal Responses, 2021 June 10. 
  *Statistical Society of Canada, Annual Conference* (Remote) &nbsp;<!--[Slides](/slides/opcg/ssc_opcg#1) -->

* Generalized Forward Sufficient Dimension Reduction for Categorical and Ordinal Responses, 2021 March 5. 
	*Stochastic Modelling And Computing* Seminar (Penn State) &nbsp;<!--[Slides](/slides/opcg/smac_opcg#1) -->

* Accurate Confidence Intervals for Clustered Data and Small Samples, 2017. 
	*The Annual Statistical Society of Canada Conference.* Meeting (Winnipeg, Canada). (Talk; Masters Work) (Was not able to attend)

* An Investigation of Composite Likelihood and Indirect Inference, 2016
	*The 4th Annual Statistical Society of Canada Student Conference.* Meeting (St. Catherines, Canada). (Poster; Masters Work)
 

:::

<!-- :::{#apps .animate__animated .animate__bounceInUp .animate__duration-faster} -->
<!-- ::: -->


<!-- :::{.animate__animated .animate__bounceInUp .animate__duration-faster .animate__delay-1s} -->
<!-- <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSetO4I9TtneTiZXNidTYHcAyqrVUeZzKAq00it7RbHMBGJ53g/viewform?embedded=true" width="100%" height="600vh" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe> -->

<!-- <br></br> -->
<!-- ::: -->

